<!DOCTYPE html>
<html>
<head>
<base href="<?php echo $this->basePath(); ?>" />
<meta charset="utf-8">
<?php echo $this->headTitle(); ?>

<?php echo $this->headLink()->prependStylesheet($this->basePath()."/css/bootstrap.css")
							->prependStylesheet($this->basePath() . '/css/style.css');?>
<!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->appendFile($this->basePath() . '/js/jquery.jcarousel.min.js')
            ->appendFile($this->basePath() . '/js/temp.js')
        ; ?>

</head>
<body>
	<div class="container container-custom">
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="#"> <img class="img-responsive" alt="Brand" src="<?php //echo $this->basePath('img/mini-hs.jpg')?>">
					</a>
				</div>
				<?php
				echo $this->navigation ( 'navigation' )->menu ()->setUlClass ( 'nav navbar-nav test pull-right main-menu' );
				?>			
			</div>
		</nav>
		
		
		
		
		
		<br>
		<div class="row"></div>
		<div class="row"><?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb.phtml');?></div>
		<div class="row">
			<div class="col-md-12"><?php echo $this->content;?></div>			
		</div>		
	</div>
	
	<!-- test loader -->
<div id="loader" style="display: none">
	<div class="spinner">
		<div class="spinner-container container1">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
		<div class="spinner-container container2">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
		<div class="spinner-container container3">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
	</div>
</div>
<?php //echo $this->view_chat_x;?>
<footer>
<div class="row">

</div>
</footer>
</body>
</html>


