<!DOCTYPE html>
<html>
<head>
<base href="<?php echo $this->basePath(); ?>" />
<meta charset="utf-8">
<?php echo $this->headTitle(); ?>

<?php echo $this->headLink()->prependStylesheet($this->basePath()."/css/bootstrap.css")
							->appendStylesheet($this->basePath() . '/css/style.css');?>
<!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->appendFile($this->basePath() . '/js/jquery.jcarousel.min.js')
            ->appendFile($this->basePath() . '/js/temp.js')
            ->appendFile($this->basePath() . '/plugin/tinymce/tinymce.min.js')
           
        ; ?>

</head>
<body>
	<div class="container container-custom">
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="#"> <img class="img-responsive" alt="Brand" src="<?php //echo $this->basePath('img/mini-hs.jpg')?>">
					</a>
				</div>
				<ul class="list-unstyled nav navbar-nav pull-right main-menu">
					<li class="login"><a href="">Đăng nhập</a></li>
				</ul>
				<?php
				echo $this->navigation ( 'navigation' )->menu ()->setUlClass ( 'nav navbar-nav test pull-right main-menu' );
				?>
					
						
			</div>
		</nav>
		
		
		
		
		
		<br>
		<div class="row"></div>
		<div class="row"><?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb.phtml');?></div>
		<div class="row">
			<div class="col-md-12"><?php echo $this->content;?></div>			
		</div>		
	</div>
	
	<!-- test loader -->
<div id="loader" style="display: none">
	<div class="spinner">
		<div class="spinner-container container1">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
		<div class="spinner-container container2">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
		<div class="spinner-container container3">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
	</div>
</div>
<!-- Modal -->
<script>
$(document).on('click','#login-pop-up-frontend',function(){
	$.post(base_url+'/news/auth/loginajax',
			{
				username:$('input[name="username"]').val(),
				password:$('input[name="password"]').val()
			},
			function(data){	
				console.log(data.logined_frontend_status);			
				if(data.logined_frontend_status==false){
					$('.anounce-login').text('Tên đăng nhập hoặc mật khẩu không đúng').css('color','red');
				}else{
					$('.anounce-login').text('Đăng nhập thành công').css('color','green');;					
				}												
			});
			
});
	$('.login').click(function(){
		$('.modal').modal('show');			
	});		
	$('.login a').click(function(e){
		e.preventDefault();
	});
	
	
</script>
<div class="modal fade">
  <div class="modal-dialog modal-edit">
    <div class="modal-content">    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Đăng nhập</h4>
      </div>      
      <div class="modal-body">
      	<div class="input-group">
  			<input type="text" class="form-control" placeholder="Username" name="username">
  			<span class="input-group-addon"><span class="glyphicon glyphicon-user glyphicon-mix"></span></span>
		</div>
		 <br>
      	<div class="input-group">
  			<input type="password" class="form-control" placeholder="Password" name="password">
  			<span class="input-group-addon"><span class="glyphicon glyphicon-lock glyphicon-mix"></span></span>
		</div>
				
	 	<span class="anounce-login"></span>
      </div>     
      <div class="modal-footer">
       <button type="button" class="btn btn-default" id="login-pop-up-frontend">Đăng nhập</button>
		<a href="<?= $this->basePath().'/news/auth/register' ?>" class="btn btn-default" id="register-frontend">Đăng ký</a>
      </div>     
    </div>    
  </div>
</div>
<footer>
<div class="row">

</div>
</footer>
</body>
</html>


