<div class="row">
	<div class="col-md-2">
		<div class="list-group">
			<a href="<?=$this->url('news/chat/manager') ?>" class="list-group-item">Quản lý
				Chat </a> 
			<a href="<?=$this->url('news/chat/banchat') ?>"
				class="list-group-item">Ban nick</a>


		</div>
	</div>
	<div class="col-md-10">
		<div class="row">
		<h3>tạm thời ban vĩnh viễn , ban theo ngày code sau</h3>
			<div class="col-md-6">
				
				<form action="<?=$this->url('news/chat/banchat') ?>" method="post">
					<label> <span>Username</span> <input name="username" type="text"
						class="form-control" required="required" value="">
					</label><br> <label> <span>Thời gian ban</span> <input
						name="time-ban" type="text" class="form-control"
						 value="" placeholder="không cần nhập">
					</label><br> <label> <span>Lý do</span> <input name="reason"
						type="text" class="form-control" value=""
						placeholder="không cần nhập">
					</label><br> <input name="submit" class=" btn btn-default"
						type="submit" value="Ban">
				</form>
			</div>
			<div class="col-md-6">
				<form action="<?=$this->url('news/chat/unbanchat') ?>" method="post">
					<label> <span>Username</span> <input name="username" type="text"
						class="form-control" required="required" value="">
					</label><br> <label> <span>Thời gian ban</span> <input
						name="time-ban" type="text" class="form-control"
						value="" placeholder="không cần nhập">
					</label><br> <label> <span>Lý do</span> <input name="reason"
						type="text" class="form-control" value=""
						placeholder="không cần nhập">
					</label><br> <input name="submit" class=" btn btn-default"
						type="submit" value="Unban">
				</form>
			</div>
		</div>


	</div>
</div>