<script type="text/javascript">
$(document).ready(function(){
	loadchat();
	checkAuth();
//setInterval(function(){loadchat()},2000);	
$('.message').keypress(function(e){
     var p = e.which;
     if(p==13){	    	 
    	 console.log($('.message').val());
    	 $.post(base_url+'/news/chat/postchat'
    			 ,{message:$('.message').val()},function(data){
    				 
    			 });
         //$('.table-message').append("<tr><td>"+$('.message').val()+"</td></tr>");
         $('.chat-content').scrollTop($('.chat-content').prop('scrollHeight'));
         $('.message').val('');
         loadchat();
     }
 });
function loadchat(){	
	$.get(base_url+'/news/chat/getchat'
			,function(data){
				var tr;
				var th="<thead><tr><th class='col-md-2'>Date Time</th><th class='col-md-2'>User</th><th class='col-md-7'>Message</th></tr></thead>";
				//console.log(data);									
				for(var i=0;i<data.chat_data.length;i++){							
					tr+="<tr><td class='td-timechat'>" +data.chat_data[i].date_time+"</td><td class='td-userchat'>"+data.chat_data[i].username+"</td><td>"+data.chat_data[i].message+"</td></tr>";						
				}
				$('.table-message').empty();
				$('.table-message').append(tr);
				$('.chat-content').scrollTop($('.chat-content').prop('scrollHeight'));
				
			}
		);
}
function checkAuth(){		
	$.get(base_url+'/news/auth/checkAuth'
			,function(data){					
					//console.log(data);
					if(data.checkAuth==false) {
						$("input[name=message]").attr('disabled','').val('Đăng nhập để chat');
						$("button[name=submit-chat]").css('visibility','hidden');					
					}
					if(data.checkAuth==true && data.checkBan==true) {
						$("input[name=message]").attr('disabled','').val('Bạn đã bị ban');
						$("button[name=submit-chat]").css('visibility','hidden');						
					}
					if(data.checkAuth==true && data.checkBan==false) {
						setInterval(function(){loadchat()},2000);
					}
				}
	);	
}
});
</script>
<div class="row">
<div class="col-md-12">
	<!-- <div class="row chat-header"><h4>Chatbox</h4></div>
	<div class="row chat-content">
		<table class="table table-message">
		<thead>
		<tr>
			<th>Date Time</th>
			<th>User</th>
			<th>Message</th>
		</tr>
		</thead>
			<tbody>
				<tr>
					<td>01-12, 09:17</td>
					<td>Tyche</td>
					<td>HELLO Word, yes it is homestock comeback soon</td>
				</tr>
				
			</tbody>
		</table>
	</div>
	<div class="row chat-panel">

		<div class="col-md-3">
			<span class="glyphicon glyphicon-font"></span> <span
				class="glyphicon glyphicon-bold"></span> <span
				class="glyphicon glyphicon-italic"></span>
			<div class="col-xs-3">
				<select class="form-control">
					<option>11px</option>
					<option>12px</option>
					<option>13px</option>
					<option>14px</option>
				</select>
			</div>
		</div>
		<div class="col-md-9">			
				<div class="col-xs-9">
					<input type="text" class="form-control message" name='message' placeholder="Nội dung">
				</div>
				<button type="submit" name='submit-chat' class="btn btn-default">Send</button>			
		</div>
	</div> -->
	<ul class="list-unstyled chat-box">
	<li class="chat-header"><span style="color: #428bca;font-weight: bold;">Welcome</span></li>
	<li class="chat-content">	
		<table class="table table-message">			
			<tbody>										
			</tbody>
		</table>	
	</li>
	<li class="chat-panel">			
				<div class="col-xs-9">
					<input type="text" class="form-control message" name='message' placeholder="Nội dung">
				</div>
				<button type="submit" name='submit-chat' class="btn btn-default">Send</button>			
		
	</li>
	</ul>
</div>
</div>