<h3>Manager page : index action</h3>
<p>Welcome :<?php echo $user->username;?></p>
<p><a href="<?php echo $this->url('news/auth/logout')?>">Logout</a></p>
<a class="btn btn-default" href="<?php echo $this->url('news/manager',array('action'=>'adduser')); ?>">Add</a>
<table class="table">
  <tr>
    <th>ID</th>
    <th>Username</th>
    <th>Password</th>    
    <th>Mail</th>
    <?php if ($user->title_user=='admin') :?> 
    <th>Edit</th>
    <th>Delete</th>
    <?php endif;?>
  </tr>
  <?php foreach ($data as $val){ ?>
  <tr>
  	<td><?=$val->id ?></td>
  	<td><?=$val->username ?></td>
  	<td><?=$val->password ?></td>
  	<td><?=$val->email ?></td>    
  	<?php if ($user->title_user=='admin') :?>  	  	
  	<td><a href="<?php echo $this->url('news/manager',array('action'=>'edit','id'=>$val->id)); ?>">Edit</a></td>
  	<td><a href="<?php echo $this->url('news/manager',array('action'=>'delete','id'=>$val->id));  ?>">Delete</a></td>
  	<?php endif;?>
  </tr>
  <?php }?>
  <tfoot>
  <tr>
  	<td colspan="6"><?php echo $this->paginationControl(
  			$this->data,'sliding',
  			array('partial/paginator.phtml','News'),
  			array('route'=>'news/manager')
  			)?></td>
  </tr>
  </tfoot>
</table>
<?php echo $this->view_chat;?>

