<h3>Test login by FACEBOOK</h3>
<?php //echo $link?>
<?php
$form=$this->form;
$form->setAttribute('action', $this->url('news/auth/register'));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('username')).'<br>';
echo $this->formRow($form->get('password')).'<br>';
echo $this->formRow($form->get('confirm_password')).'<br>';
echo $this->formRow($form->get('email')).'<br>';
echo $this->formRow($form->get('captcha')).'<br>';
echo $this->formRow($form->get('submit')).'<br>';
echo $this->formRow($form->get('csrf')).'<br>';
echo $this->form()->closeTag($form);
//echo print_r($data);
?>