<h3>This is login page</h3>
<?php 
$form=$this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('username')).'<br>';
echo $this->formElementErrors($form->get('username'));

echo $this->formRow($form->get('password')).'<br>';
echo $this->formElementErrors($form->get('password'));
echo $this->formRow($form->get('remember')).'<br>';
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag($form);
echo $this->messages;
?>
<a href="<?=$link_login_fb ?>">Facebook</a>